### ISSUE TITLE
Cannot build the code

### ISSUE THREAD

**Issue by MengleiZhang** [SoonyangZhang/webrtc-gcc-ns3#1]
Hi Soonyang,

Thank you for sharing the WebRTC module to the ns-3 community. I found the following issues when building the code from this Github.

1. I was able to run “gclient sync” and build the WebRTC from the default branch. However, after I switch to the m84 branch and executed “gclient sync”, the code does not build successfully. Could you take a look? If there are issues with the m84 branch, could you update the ns-3 code to support the latest WebRTC?
2. In the NS3 part, step 4. After I updated the configuration code in the wscript, some references are still missing. Could you double check? If I understand correctly, some h files are referenced from the WebRTC code, but why you also copied some h files to the ex-webrtc folder? E.g., the h files in test and api folder.

**Comment by SoonyangZhang** [comment]
This repo depends on webrtc m84, please build it first.  To intergrate webrtc and ns3, I refer the code under /webrtc/test/scenario, It is small discrete event simulator and only suports build two node topology (webrtc/test/scenario/network_node.cc). That's why I copy some code in test and api here.  You could take reference test/scenario/call_client.cc to make change on ex-webrtc, if you intend to build official webrtc once the files under webrtc/test/scenario/ are changed in official webrtc.  These files are not built in libwebrtc.a when rtc_include_tests=false.

**Comment by SoonyangZhang** [comment]
@MengleiZhang  If you still can not get the code running successfully, let me know and I am glad to upload the m84 webrtc code.

**Comment by MengleiZhang** [comment]
Nope. I would appreciate if you can upload the m84 WebRTC code. Maybe I am missing some prerequisite software in my computer, since I am not familiar with WebRTC.

**Comment by SoonyangZhang** [comment]
@MengleiZhang  install clang and build ns3 with clang++. 
link: https://pan.baidu.com/s/18F26BAmZhj_CAQzKNUeDSA      
auth code: j4ts     
decompression: cat webrtc.tar.gz* |tar zx    
The modification on webrtc is already made and the tip on **Preparation** of 1, 2,3,4,5 is no need. The webrtc code I upload is already built. So the tip on **Build webrtc** can be skipped.

**Comment by MengleiZhang** [comment]
Thanks for sharing the WebRTC code. I was able to build the WebRTC code after the following steps:

1. installed clang++ and python. (`alias python=python2` will return errors when building WebRTC);
2. executed `./build/install-build-deps.sh`
3. cloned the depot_tools repo and switched to refs/remotes/origin/chrome/4147, i.e., `git checkout -b m84 refs/remotes/origin/chrome/4147`

When building the ns-3, the following errors show up. See the [error message](https://github.com/SoonyangZhang/webrtc-gcc-ns3/files/6498267/error.txt) for more details. Moreover, I cannot find the following two files. The webrtc folder does not exist.


1. //third_party/webrtc/modules/rtp_rtcp/source/rtp_rtcp_impl.cc   
2. //third_party/webrtc/call/call.h

**Comment by SoonyangZhang** [comment]
I am wondering if you download the code I upload. If you do, I think it it is not necessary to rebuit the libwebrtc and add the envrionental variable WEBRTC_SRC_DIR will do. Since the libwertc.a can be found under webrtc/src/out/m84/obj/. 
If you intend to rebuilt the webrtc code, just:
```
cd webrtc/src/  
gn gen out/m84 --args='is_debug=false is_component_build=false is_clang=true rtc_include_tests=false rtc_use_h264=true rtc_enable_protobuf=false use_rtti=true use_custom_libcxx=false treat_warnings_as_errors=false use_ozone=true'     
ninja -C out/m84   
```
I  really do not know where the three tips comes from? And my advice is just gettting the code running first. 

> 1. installed clang++ and python. (alias python=python2 will return errors when building WebRTC);
2. executed ./build/install-build-deps.sh
3. cloned the depot_tools repo and switched to refs/remotes/origin/chrome/4147, i.e., git checkout -b m84 refs/remotes/origin/chrome/4147


QQ: 865678017

**Comment by MengleiZhang** [comment]
Sorry about the confusion. I was trying to say that I can build the official WebRTC code after the three steps in my previous thread. I followed the updated instructions in README, but now the errors show up when building the ns3 code by running `./waf build  `. Here is the [Error Message](https://github.com/SoonyangZhang/webrtc-gcc-ns3/files/6505462/error.txt).

**Comment by SoonyangZhang** [comment]
@MengleiZhang  It seems the webrtc code base is a newer version. My sugestion is to build the webrtc codebase I upload and running it first. If you insist with the webrtc code you download, you may update some code in ex-webrtc module after you are famililar with the webrtc code.   As for the official  webrtc code, I am sorry and I have no time to update the ex-webrtc module. If you build the webrtc code I upload and encountering any error, I am gald to provide help.

**Comment by MengleiZhang** [comment]
I am having this issue with the webrtc m84 version (following the instructions in the readme), not the newer version. Really appreciate your help, but I think I will drop this project since it takes too much efforts for me as a WebRTC newbie :)

**Comment by MengleiZhang** [comment]
Would it be possible for you to provide an version for simulation mode only? I assume this approach will not need to install webrtc.

**Comment by SoonyangZhang** [comment]
@MengleiZhang    I upload the header and libwebrtc.a.
url: https://pan.baidu.com/s/1WAwxKjNg67deHrubYl1jFA 
auth code: h21w
Just unzip the file and configure WEBRTC_SRC_DIR=/xx/xx/xx/webrtc/src  
Then you can build the ex-webrtc in ns3.
Hope this help.
